package com.mycompany.semestre3.unidad3.adminPack;

import com.mycompany.semestre3.unidad3.adminPack.utils.*;

public class MainForm extends javax.swing.JFrame {
    /* Atributos */
    Pila pila = new Pila();
    
    /* Metodos */
    /**
     * Constructor
     */
    public MainForm() {
        initComponents();
        configWin();
    }
    
    /**
     * Algunos ajustes en la ventana
     */
    private void configWin() {
        //this.setResizable(false);
        this.setLocationRelativeTo(null);
    }
    
    private void updateTable() {
        tabla.setModel(pila.getAsTable());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        WinBg = new javax.swing.JPanel();
        sideMenu = new javax.swing.JPanel();
        titleOfSide = new javax.swing.JLabel();
        appendOpt = new javax.swing.JLabel();
        deleteOpt = new javax.swing.JLabel();
        listAllOpt = new javax.swing.JLabel();
        helpOpt = new javax.swing.JLabel();
        exitAppOpt = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabla = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        WinBg.setBackground(new java.awt.Color(51, 51, 51));
        WinBg.setForeground(new java.awt.Color(204, 204, 204));

        sideMenu.setBackground(new java.awt.Color(0, 153, 255));
        sideMenu.setForeground(new java.awt.Color(255, 255, 255));

        titleOfSide.setFont(new java.awt.Font("SansSerif", 3, 36)); // NOI18N
        titleOfSide.setForeground(new java.awt.Color(255, 255, 255));
        titleOfSide.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titleOfSide.setText("AdminPack");

        appendOpt.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        appendOpt.setForeground(new java.awt.Color(255, 255, 255));
        appendOpt.setIcon(new javax.swing.ImageIcon("/home/diego/NetBeans-Proyects/Estructura-de-Datos/src/main/java/com/mycompany/semestre3/unidad3/adminPack/images/x32/agregar.png")); // NOI18N
        appendOpt.setText("Agregar");
        appendOpt.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        appendOpt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                appendOptMouseClicked(evt);
            }
        });

        deleteOpt.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        deleteOpt.setForeground(new java.awt.Color(255, 255, 255));
        deleteOpt.setIcon(new javax.swing.ImageIcon("/home/diego/NetBeans-Proyects/Estructura-de-Datos/src/main/java/com/mycompany/semestre3/unidad3/adminPack/images/x32/borrar.png")); // NOI18N
        deleteOpt.setText("Eliminar");
        deleteOpt.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        deleteOpt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                deleteOptMouseClicked(evt);
            }
        });

        listAllOpt.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        listAllOpt.setForeground(new java.awt.Color(102, 102, 102));
        listAllOpt.setIcon(new javax.swing.ImageIcon("/home/diego/NetBeans-Proyects/Estructura-de-Datos/src/main/java/com/mycompany/semestre3/unidad3/adminPack/images/x32/lista.png")); // NOI18N
        listAllOpt.setText("Listar");
        listAllOpt.setCursor(new java.awt.Cursor(java.awt.Cursor.WAIT_CURSOR));

        helpOpt.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        helpOpt.setForeground(new java.awt.Color(255, 255, 255));
        helpOpt.setIcon(new javax.swing.ImageIcon("/home/diego/NetBeans-Proyects/Estructura-de-Datos/src/main/java/com/mycompany/semestre3/unidad3/adminPack/images/x32/solicitud.png")); // NOI18N
        helpOpt.setText("Ayuda");
        helpOpt.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        helpOpt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                helpOptMouseClicked(evt);
            }
        });

        exitAppOpt.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        exitAppOpt.setForeground(new java.awt.Color(255, 102, 102));
        exitAppOpt.setIcon(new javax.swing.ImageIcon("/home/diego/NetBeans-Proyects/Estructura-de-Datos/src/main/java/com/mycompany/semestre3/unidad3/adminPack/images/x32/salir.png")); // NOI18N
        exitAppOpt.setText("Salir");
        exitAppOpt.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        exitAppOpt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                exitAppOptMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout sideMenuLayout = new javax.swing.GroupLayout(sideMenu);
        sideMenu.setLayout(sideMenuLayout);
        sideMenuLayout.setHorizontalGroup(
            sideMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(titleOfSide, javax.swing.GroupLayout.DEFAULT_SIZE, 259, Short.MAX_VALUE)
            .addGroup(sideMenuLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(sideMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(appendOpt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(deleteOpt, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(listAllOpt, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(helpOpt, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(exitAppOpt, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        sideMenuLayout.setVerticalGroup(
            sideMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sideMenuLayout.createSequentialGroup()
                .addComponent(titleOfSide, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(appendOpt, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(deleteOpt, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(listAllOpt, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 383, Short.MAX_VALUE)
                .addComponent(helpOpt, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(exitAppOpt, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        tabla.setBackground(new java.awt.Color(51, 51, 51));
        tabla.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(102, 102, 102), 1, true));
        tabla.setForeground(new java.awt.Color(204, 204, 204));
        tabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tabla.setGridColor(new java.awt.Color(51, 51, 51));
        jScrollPane1.setViewportView(tabla);

        jLabel1.setFont(new java.awt.Font("SansSerif", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Pila de articulos");

        javax.swing.GroupLayout WinBgLayout = new javax.swing.GroupLayout(WinBg);
        WinBg.setLayout(WinBgLayout);
        WinBgLayout.setHorizontalGroup(
            WinBgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(WinBgLayout.createSequentialGroup()
                .addComponent(sideMenu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 109, Short.MAX_VALUE)
                .addGroup(WinBgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 549, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 549, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(96, 96, 96))
        );
        WinBgLayout.setVerticalGroup(
            WinBgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(sideMenu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(WinBgLayout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(WinBg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(WinBg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /* Eventos */
    /**
     * Evento para cerrar la aplicacion.
     * @param evt 
     */
    private void exitAppOptMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitAppOptMouseClicked
        if(ExitDialog.showDialog(this) == 1) {
            System.exit(0);
        }
    }//GEN-LAST:event_exitAppOptMouseClicked

    /**
     * Evento para invocar la ventana de ayuda
     * @param evt 
     */
    private void helpOptMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_helpOptMouseClicked
        HelpDialog.showDialog(this);
    }//GEN-LAST:event_helpOptMouseClicked

    /**
     * Evento para agregar un articulo y actualizar la lista.
     * 
     * @param evt 
     */
    private void appendOptMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_appendOptMouseClicked
        Articulo articulo = new Articulo();
        
        if(AppendObjDialog.showDialog(this, articulo) == 1) {
            pila.push(articulo);
            updateTable();
        }
            
    }//GEN-LAST:event_appendOptMouseClicked

    /**
     * Evento para eliminar de la pila.
     * @param evt 
     */
    private void deleteOptMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_deleteOptMouseClicked
        if(DeleteObjDialog.showDialog(this) == 1) {
            pila.pop();
            updateTable();
        }
        
        //ErrorDialog.showDialog(this, "Funcion no implementada", "<html><body>Esta funcion no ha sido implementada!<br>Prueve con otra</body></html>");
    }//GEN-LAST:event_deleteOptMouseClicked

    /**
     * Main
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel WinBg;
    private javax.swing.JLabel appendOpt;
    private javax.swing.JLabel deleteOpt;
    private javax.swing.JLabel exitAppOpt;
    private javax.swing.JLabel helpOpt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel listAllOpt;
    private javax.swing.JPanel sideMenu;
    private javax.swing.JTable tabla;
    private javax.swing.JLabel titleOfSide;
    // End of variables declaration//GEN-END:variables
}
