package com.d.thefinalproyect;

import com.d.thefinalproyect.grapUtils.RoundedPanel;
import com.d.thefinalproyect.grapUtils.BasicDialogs;
import com.d.thefinalproyect.grapUtils.WindowTemplate;

import com.d.thefinalproyect.more.Libro;
import com.d.thefinalproyect.more.DateUtils;
import java.util.TreeSet;

public class PageAdd extends RoundedPanel implements WindowTemplate {
    ///
    /// Atributos
    ///
    private TreeSet<Libro> treebooks;
    
    ///
    /// Metodos
    ///
    /** Constructor */
    public PageAdd(TreeSet tree) {
        super(40);
        initComponents();
        
        this.treebooks = tree;
        
        windowConfig();
    }
    
    @Override
    public void windowConfig() {
        dummydata.setVisible(true);
    }

    /**
     * Limpia los campos de texto
     */
    @Override
    public void clearInputs() {
        this.tituloField.setText("");
        this.isbnField.setText("");
        this.paginasField.setText("");
        this.editorialField.setText("");
        this.autorField.setText("");
        
        this.dayField.setSelectedIndex(0);
        this.monthField.setSelectedIndex(0);
        this.yearField.setSelectedIndex(0);
    }
    
    /**
     * Valida cada uno de los campos
     */
    @Override
    public boolean validateFields() {
        /// Validar fecha
        String day = (String)this.dayField.getSelectedItem();
        String month = (String)this.monthField.getSelectedItem();
        String year = (String)this.yearField.getSelectedItem();
        
        if(!DateUtils.validateDate(day, month, year)) {
            BasicDialogs.warning(this, "La fecha ingresada no es valida", "Fecha invalida");
            return false;
        }
        
        /// Validar Numero de paginas
        try {
            Integer.parseInt(this.paginasField.getText());
        } catch(Exception e) {
            BasicDialogs.warning(this, "No se ingreso un numero de paginas correcto", "Numero de paginas invalido");
            return false;
        }
        
        /// Validar ISBN
        try {
            Integer.parseInt(this.isbnField.getText());
        } catch(Exception e) {
            BasicDialogs.warning(this, "El ISBN no es valido, intente de nuevo por favor", "ISBN invalido");
            return false;
        }
        
        /// Validar el resto de campos
        if((!tituloField.getText().isBlank() && !editorialField.getText().isBlank() && !autorField.getText().isBlank()) == false) {
            BasicDialogs.warning(this, "Por favor, rellene los campos faltantes", "Campos faltantes");
            return false;
        }
        
        return true;
    }

    @Override
    public void close() {
        // Do Nothing!
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new RoundedPanel(30);
        tituloField = new javax.swing.JTextField();
        isbnField = new javax.swing.JTextField();
        paginasField = new javax.swing.JTextField();
        dayField = new javax.swing.JComboBox<>();
        monthField = new javax.swing.JComboBox<>();
        yearField = new javax.swing.JComboBox<>();
        editorialField = new javax.swing.JTextField();
        autorField = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        aceptar = new javax.swing.JButton();
        cancelar = new javax.swing.JButton();
        dummydata = new javax.swing.JLabel();

        setBackground(new java.awt.Color(63, 56, 66));

        jLabel1.setFont(new java.awt.Font("sansserif", 1, 36)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/x48/AppBarToggleButton.png"))); // NOI18N
        jLabel1.setText("Agregar");

        jPanel1.setBackground(new java.awt.Color(63, 56, 66));

        tituloField.setSelectionColor(new java.awt.Color(0, 102, 204));

        dayField.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31" }));

        monthField.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Enero", "Febrero", "Marzo", "Abril", "Mayo", "Junio", "Julio", "Agosto", "Septiembre", "Octubre", "Noviembre", "Diciembre" }));

        yearField.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "2024", "2023", "2022", "2021", "2020", "2019", "2018", "2017", "2016", "2015", "2014", "2013", "2012", "2011", "2010", "2009", "2008", "2007", "2006", "2005", "2004", "2003", "2002", "2001", "2000", "1999", "1998", "1997", "1996", "1995", "1994", "1993", "1992", "1991", "1990", "1989", "1988", "1987", "1986", "1985", "1984", "1983", "1982", "1981", "1980", "1979", "1978", "1977", "1976", "1975", "1974", "1973", "1972", "1971", "1970", "Antes de 1970" }));

        jLabel2.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(153, 153, 153));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel2.setText("Titulo");

        jLabel3.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(153, 153, 153));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel3.setText("ISBN");

        jLabel4.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(153, 153, 153));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel4.setText("No de paginas");

        jLabel5.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(153, 153, 153));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel5.setText("Fecha");

        jLabel6.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(153, 153, 153));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel6.setText("Editorial");

        jLabel7.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(153, 153, 153));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel7.setText("Autor");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 119, Short.MAX_VALUE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(dayField, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(monthField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(yearField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(paginasField)
                    .addComponent(isbnField)
                    .addComponent(tituloField)
                    .addComponent(autorField)
                    .addComponent(editorialField, javax.swing.GroupLayout.PREFERRED_SIZE, 351, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tituloField, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(isbnField, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(14, 14, 14)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(paginasField, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(dayField, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(monthField, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(yearField, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(editorialField, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(autorField, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addContainerGap(51, Short.MAX_VALUE))
        );

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/others/simplebook.png"))); // NOI18N

        aceptar.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        aceptar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/x24/AppBarButton.png"))); // NOI18N
        aceptar.setText("Guardar");
        aceptar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        aceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aceptarActionPerformed(evt);
            }
        });

        cancelar.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        cancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/x24/ImplicitTransition.png"))); // NOI18N
        cancelar.setText("Cancelar");
        cancelar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelarActionPerformed(evt);
            }
        });

        dummydata.setBackground(new java.awt.Color(102, 102, 102));
        dummydata.setText("create a dummy data");
        dummydata.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                dummydataMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 301, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 19, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(dummydata)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(cancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(aceptar, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(53, 53, 53)
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 328, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 70, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(aceptar, javax.swing.GroupLayout.DEFAULT_SIZE, 56, Short.MAX_VALUE)
                        .addComponent(cancelar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(dummydata, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Evento de "acpetar" para poder crear un objeto de tipo
     * Libro y guardarlo en el arbol.
     * 
     * @param evt 
     */
    private void aceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aceptarActionPerformed
        if(!validateFields()) return;
        
        Libro libro = new Libro(
                this.tituloField.getText(),
                Integer.parseInt(this.isbnField.getText()),
                Integer.parseInt(this.paginasField.getText()),
                dayField.getSelectedItem()+"/"+monthField.getSelectedItem()+"/"+yearField.getSelectedItem(),
                this.editorialField.getText(),
                this.autorField.getText()
        );
        
        if(treebooks.add(libro)) {
            BasicDialogs.info(this, "El libro se agrego correctamente al arbol", "Listo");
            clearInputs();
        }
        else {
            BasicDialogs.warning(this, "No se pudo agregar el libro al arbol \nIntentelo de nuevo", "Advertencia");
        }
        
    }//GEN-LAST:event_aceptarActionPerformed

    /**
     * Cancelar y borrar los datos del arbol.
     * @param evt 
     */
    private void cancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelarActionPerformed
        clearInputs();
    }//GEN-LAST:event_cancelarActionPerformed

    /**
     * Evento para crear datos fake para pruevas.
     * 
     * Esto solo se puede invocar una vez y es 
     * perfecto para las pruevas
     * @param evt 
     */
    private void dummydataMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dummydataMouseClicked
        treebooks.add(new Libro("Cien Años de Soledad", 12345, 417, "1967-05-30", "Editorial Sudamericana", "Gabriel García Márquez"));
        treebooks.add(new Libro("El Principito", 67890, 96, "1943-04-06", "Reynal & Hitchcock", "Antoine de Saint-Exupéry"));
        treebooks.add(new Libro("Los Robots del Futuro", 54321, 312, "2023-07-15", "FutureTech Books", "Alex Martínez"));
        treebooks.add(new Libro("La Sombra del Viento", 11223, 544, "2001-06-05", "Planeta", "Carlos Ruiz Zafón"));
        treebooks.add(new Libro("1984", 13579, 328, "1949-06-08", "Secker & Warburg", "George Orwell"));
        treebooks.add(new Libro("El Alquimista", 24680, 208, "1988-04-25", "HarperOne", "Paulo Coelho"));
        treebooks.add(new Libro("Orgullo y Prejuicio", 98765, 279, "1813-01-28", "T. Egerton", "Jane Austen"));
        treebooks.add(new Libro("Matar a un Ruiseñor", 87654, 336, "1960-07-11", "J.B. Lippincott & Co.", "Harper Lee"));
        treebooks.add(new Libro("El Hobbit", 76543, 310, "1937-09-21", "Allen & Unwin", "J.R.R. Tolkien"));
        treebooks.add(new Libro("Fahrenheit 451", 65432, 249, "1953-10-19", "Ballantine Books", "Ray Bradbury"));
        treebooks.add(new Libro("La Metamorfosis", 54312, 201, "1915-10-10", "Kurt Wolff Verlag", "Franz Kafka"));
        treebooks.add(new Libro("Don Quijote de la Mancha", 43210, 863, "1605-01-16", "Francisco de Robles", "Miguel de Cervantes"));
        treebooks.add(new Libro("Crónica de una Muerte Anunciada", 32109, 122, "1981-05-19", "Editorial Sudamericana", "Gabriel García Márquez"));
        treebooks.add(new Libro("El Castillo Ambulante", 21098, 448, "1986-04-01", "Greenwillow Books", "Diana Wynne Jones"));
        treebooks.add(new Libro("Drácula", 10987, 418, "1897-05-26", "Archibald Constable and Company", "Bram Stoker"));
        treebooks.add(new Libro("La Divina Comedia", 99887, 712, "1320-01-01", "Tipografía Medicea", "Dante Alighieri"));
        treebooks.add(new Libro("El Retrato de Dorian Gray", 88776, 224, "1890-07-20", "Lippincott's Monthly Magazine", "Oscar Wilde"));
        treebooks.add(new Libro("Cumbres Borrascosas", 77665, 416, "1847-12-01", "Thomas Cautley Newby", "Emily Brontë"));
        treebooks.add(new Libro("La Iliada", 66554, 560, "800-BC", "Unknown", "Homero"));
        treebooks.add(new Libro("El Nombre del Viento", 55443, 662, "2007-03-27", "DAW Books", "Patrick Rothfuss"));
        treebooks.add(new Libro("El Señor de los Anillos", 44332, 1178, "1954-07-29", "Allen & Unwin", "J.R.R. Tolkien"));
        treebooks.add(new Libro("El Código Da Vinci", 33221, 489, "2003-04-03", "Doubleday", "Dan Brown"));
        treebooks.add(new Libro("Los Juegos del Hambre", 22110, 374, "2008-09-14", "Scholastic Press", "Suzanne Collins"));
        treebooks.add(new Libro("Percy Jackson y el Ladrón del Rayo", 11009, 377, "2005-06-28", "Disney-Hyperion", "Rick Riordan"));
        treebooks.add(new Libro("Cazadores de Sombras: Ciudad de Hueso", 10088, 485, "2007-03-27", "Margaret K. McElderry Books", "Cassandra Clare"));
        treebooks.add(new Libro("El Señor de los Anillos", 44332, 1178, "1954-07-29", "Allen & Unwin", "J.R.R. Tolkien"));
        treebooks.add(new Libro("Aprender C en 21 días", 123456789, 600, "1995-05-15", "Editorial Prentice Hall", "Peter Aitken"));
        treebooks.add(new Libro("Aprender C en 21 días", 123456789, 600, "1995-05-15", "Prentice Hall", "Peter Aitken"));
        treebooks.add(new Libro("Java: The Complete Reference", 9780552, 1248, "2014-04-22", "McGraw-Hill", "Herbert Schildt"));
        treebooks.add(new Libro("Python Crash Course", 9779288, 544, "2019-05-03", "No Starch Press", "Eric Matthes"));
        treebooks.add(new Libro("Clean Code: A Handbook of Agile Software Craftsmanship", 9784, 464, "2008-08-11", "Prentice Hall", "Robert C. Martin"));
        treebooks.add(new Libro("Effective C++: 55 Specific Ways to Improve Your Programs and Designs", 97804879, 320, "2005-05-22", "Addison-Wesley", "Scott Meyers"));
        treebooks.add(new Libro("You Don't Know JS: Scope & Closures", 9704152, 98, "2014-03-17", "O'Reilly Media", "Kyle Simpson"));
        treebooks.add(new Libro("The Pragmatic Programmer: Your Journey to Mastery", 977059, 352, "2019-09-13", "Addison-Wesley", "David Thomas, Andrew Hunt"));
        treebooks.add(new Libro("Design Patterns: Elements of Reusable Object-Oriented Software", 9633610, 395, "1994-10-31", "Addison-Wesley", "Erich Gamma, Richard Helm, Ralph Johnson, John Vlissides"));
        treebooks.add(new Libro("Head First Java", 978059605, 720, "2005-02-09", "O'Reilly Media", "Kathy Sierra, Bert Bates"));
        treebooks.add(new Libro("The Art of Computer Programming, Vol. 1: Fundamental Algorithms", 9896831, 672, "1997-07-26", "Addison-Wesley", "Donald E. Knuth"));

        
        BasicDialogs.dialog(this, "Datos de prueva agregados", "");
        
        dummydata.setEnabled(false);
    }//GEN-LAST:event_dummydataMouseClicked

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton aceptar;
    private javax.swing.JTextField autorField;
    private javax.swing.JButton cancelar;
    private javax.swing.JComboBox<String> dayField;
    private javax.swing.JLabel dummydata;
    private javax.swing.JTextField editorialField;
    private javax.swing.JTextField isbnField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JComboBox<String> monthField;
    private javax.swing.JTextField paginasField;
    private javax.swing.JTextField tituloField;
    private javax.swing.JComboBox<String> yearField;
    // End of variables declaration//GEN-END:variables
}
