package com.d.thefinalproyect;

import com.d.thefinalproyect.grapUtils.RoundedPanel;
import com.d.thefinalproyect.grapUtils.WindowTemplate;

import com.d.thefinalproyect.more.CompareByAutor;
import com.d.thefinalproyect.more.CompareByEditorial;
import com.d.thefinalproyect.more.CompareByISBN;
import com.d.thefinalproyect.more.CompareByPages;
import com.d.thefinalproyect.more.CompareByTitle;
import com.d.thefinalproyect.more.Libro;
import com.d.thefinalproyect.more.Others;
import java.util.TreeSet;

public class PageList extends RoundedPanel implements WindowTemplate {
    ///
    /// Atributos
    ///
    static int ORDER_BY_TITLE = 0;
    static int ORDER_BY_AUTOR = 1;
    static int ORDER_BY_ISBN = 3;
    static int ORDER_BY_PAGES = 4;
    
    private TreeSet<Libro> treebooks;
    
    ///
    /// Metodos
    ///
    /** Constructor */
    public PageList(TreeSet tree) {
        super(40);
        initComponents();
        
        treebooks = tree;
        
        windowConfig();
    }
    
    private void showTree() {
        table.setModel(Others.treeToTable(treebooks));
    }
    
    @Override
    public void windowConfig() {
        showTree();
    }

    @Override
    public void clearInputs() {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }

    @Override
    public boolean validateFields() {
        return treebooks.isEmpty();
    }

    @Override
    public void close() {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }

    ///
    /// Inicializacion de los elementos
    ///
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        listarTitulo = new javax.swing.JButton();
        listarPorISBN = new javax.swing.JButton();
        listarPorPaginas = new javax.swing.JButton();
        listarPorAutores = new javax.swing.JButton();

        setBackground(new java.awt.Color(63, 56, 66));

        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(table);

        jLabel1.setFont(new java.awt.Font("sansserif", 1, 36)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/x48/TreeView.png"))); // NOI18N
        jLabel1.setText("Lista");

        listarTitulo.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        listarTitulo.setForeground(new java.awt.Color(204, 204, 204));
        listarTitulo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/x32/TextBlock.png"))); // NOI18N
        listarTitulo.setText("Por titulo");
        listarTitulo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        listarTitulo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                listarTituloActionPerformed(evt);
            }
        });

        listarPorISBN.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        listarPorISBN.setForeground(new java.awt.Color(204, 204, 204));
        listarPorISBN.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/x32/InfoBadge.png"))); // NOI18N
        listarPorISBN.setText("Por ISBN");
        listarPorISBN.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        listarPorISBN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                listarPorISBNActionPerformed(evt);
            }
        });

        listarPorPaginas.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        listarPorPaginas.setForeground(new java.awt.Color(204, 204, 204));
        listarPorPaginas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/x32/ImplicitTransition.png"))); // NOI18N
        listarPorPaginas.setText("Por paginas");
        listarPorPaginas.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        listarPorPaginas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                listarPorPaginasActionPerformed(evt);
            }
        });

        listarPorAutores.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        listarPorAutores.setForeground(new java.awt.Color(204, 204, 204));
        listarPorAutores.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/x32/PersonPicture.png"))); // NOI18N
        listarPorAutores.setText("Por Autores");
        listarPorAutores.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        listarPorAutores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                listarPorAutoresActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 832, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(listarTitulo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(listarPorISBN)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(listarPorPaginas)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(listarPorAutores)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(listarTitulo)
                    .addComponent(listarPorISBN)
                    .addComponent(listarPorPaginas)
                    .addComponent(listarPorAutores))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 459, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void listarTituloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_listarTituloActionPerformed
        if(validateFields()) return;
        treebooks = Others.transformTree(treebooks, new CompareByTitle());
        showTree();
    }//GEN-LAST:event_listarTituloActionPerformed

    private void listarPorISBNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_listarPorISBNActionPerformed
        if(validateFields()) return;
        treebooks = Others.transformTree(treebooks, new CompareByISBN());
        showTree();
    }//GEN-LAST:event_listarPorISBNActionPerformed

    private void listarPorPaginasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_listarPorPaginasActionPerformed
        if(validateFields()) return;
        treebooks = Others.transformTree(treebooks, new CompareByPages());
        showTree();
    }//GEN-LAST:event_listarPorPaginasActionPerformed

    private void listarPorAutoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_listarPorAutoresActionPerformed
        if(validateFields()) return;
        treebooks = Others.transformTree(treebooks, new CompareByAutor());
        showTree();
    }//GEN-LAST:event_listarPorAutoresActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton listarPorAutores;
    private javax.swing.JButton listarPorISBN;
    private javax.swing.JButton listarPorPaginas;
    private javax.swing.JButton listarTitulo;
    private javax.swing.JTable table;
    // End of variables declaration//GEN-END:variables

}
