package com.mycompany.semestre3.unidad2.AlmacenMexico;

import javax.swing.JOptionPane;

public class WinShop extends javax.swing.JInternalFrame {

    /* ------==[ Atributos ]==------ */
    ControlArticulo control = null;

    /**
     * CONSTRUCTOR
     */
    public WinShop(ControlArticulo control) {
        initComponents();
        
        this.control = control;
        
        this.setClosable(true);
        this.setVisible(true);
        
        checkTable();
    }
    
    private void checkTable() {
        if(control.getEnumTable().getRowCount() < 1) {
            JOptionPane.showMessageDialog(null, "No hay articulos agregados en el sistema.", "Advertencia", JOptionPane.ERROR_MESSAGE);
            this.setVisible(false);
        }
        else {
            this.tabla.setModel(control.getEnumTable());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        winBackground = new javax.swing.JPanel();
        winTitleTag = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabla = new javax.swing.JTable();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel1 = new javax.swing.JLabel();
        idProductIn = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        cantidadIn = new javax.swing.JSpinner();
        comprarBtn = new javax.swing.JButton();

        winBackground.setBackground(new java.awt.Color(51, 51, 51));
        winBackground.setForeground(new java.awt.Color(255, 255, 255));

        winTitleTag.setFont(new java.awt.Font("Noto Sans", 1, 18)); // NOI18N
        winTitleTag.setForeground(new java.awt.Color(255, 255, 255));
        winTitleTag.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        winTitleTag.setText("COMPRA DE ARTICULOS");

        tabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(tabla);

        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);

        jLabel1.setForeground(new java.awt.Color(204, 204, 204));
        jLabel1.setText("Id del articulo a comprar");

        jLabel2.setForeground(new java.awt.Color(204, 204, 204));
        jLabel2.setText("Cantidad de articulos");

        cantidadIn.setFocusCycleRoot(true);

        comprarBtn.setText("COMPRAR");
        comprarBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comprarBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout winBackgroundLayout = new javax.swing.GroupLayout(winBackground);
        winBackground.setLayout(winBackgroundLayout);
        winBackgroundLayout.setHorizontalGroup(
            winBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(winTitleTag, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(winBackgroundLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 431, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(winBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cantidadIn)
                    .addGroup(winBackgroundLayout.createSequentialGroup()
                        .addComponent(idProductIn, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, winBackgroundLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(winBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(comprarBtn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );
        winBackgroundLayout.setVerticalGroup(
            winBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(winBackgroundLayout.createSequentialGroup()
                .addComponent(winTitleTag, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(winBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(winBackgroundLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(winBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 355, Short.MAX_VALUE)
                            .addComponent(jSeparator1)))
                    .addGroup(winBackgroundLayout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(idProductIn, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cantidadIn, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 127, Short.MAX_VALUE)
                        .addComponent(comprarBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(winBackground, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(winBackground, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void comprarBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comprarBtnActionPerformed
        int id = 0;
        int cantidad = 0;
            
        try {
            id =  Integer.parseInt(this.idProductIn.getText());
            cantidad = Integer.parseInt(this.cantidadIn.getValue()+"");
            
            if(cantidad < 1) {
                JOptionPane.showMessageDialog(null, "No puedes ingresar numeros negativos. \nRevisa la compra y corrije el error.", "Error al leer datos", JOptionPane.ERROR_MESSAGE);
                return;
            }
            
            if(control.updateExistencia(id, cantidad)) {
                JOptionPane.showMessageDialog(null, "Se ha enviado la orden y la transaccion se ha completado.", "Transaccion completa", JOptionPane.CLOSED_OPTION);
                this.setVisible(false);
                this.setClosed(true);    
            }
            else {
                JOptionPane.showMessageDialog(null, "Verifique los datos y corrijalos", "Error de transaccion", JOptionPane.ERROR_MESSAGE);
            }
            
        }
        catch(Exception e) {
            JOptionPane.showMessageDialog(null, "Error a la hora de realizar la transaccion: \n"+e.getMessage(), "Error: "+e.getClass(), JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_comprarBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JSpinner cantidadIn;
    private javax.swing.JButton comprarBtn;
    private javax.swing.JTextField idProductIn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTable tabla;
    private javax.swing.JPanel winBackground;
    private javax.swing.JLabel winTitleTag;
    // End of variables declaration//GEN-END:variables
}
