package com.mycompany.semestre3.unidad3.adminPack.utils;

import com.mycompany.semestre3.unidad3.adminPack.Articulo;

public class AppendObjDialog extends javax.swing.JDialog {
    /* Atributos */
    private DialogWinRequest request;
    private Articulo articulo;
    private java.awt.Frame parent;

    /**
     * Constructor por defecto.
     */
    public AppendObjDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        
        this.setLocationRelativeTo(null);
        this.setResizable(false);
        
        this.parent = parent;
    }
    
    /**
     * Setter de articulo (debe ser una referencia)
     * @param articulo 
     */
    public void setArticulo(Articulo articulo) {
        this.articulo = articulo;
    }
    
    /**
     * Le pasamos el atributo para establecer la comunicacion
     * y poder obtener una respuesta de acuerdo al parametro 
     * por referencia y el boton pulsado.
     * 
     * @param r 
     */
    public void setUserRequest(DialogWinRequest r) {
        this.request = r;
        request.windowClosedOrHiden();
    }
    
    /**
     * Mostramos el dialogo, pero esta aun mas simplificado
     * y es mas facil de llamar.
     * @param parent
     * @return 
     */
    public static int showDialog(java.awt.Frame parent, Articulo articulo) {
        DialogWinRequest request = new DialogWinRequest();
        
        AppendObjDialog subwin = new AppendObjDialog(parent, true);
        subwin.setArticulo(articulo);
        subwin.setUserRequest(request);
        subwin.setVisible(true);
        
        return request.getRequest();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        winBg = new javax.swing.JPanel();
        okBtn = new javax.swing.JButton();
        cancelBtn = new javax.swing.JButton();
        message = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        nombreIn = new javax.swing.JTextField();
        codigoIn = new javax.swing.JTextField();
        precioIn = new javax.swing.JTextField();
        stockIn = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        winBg.setBackground(new java.awt.Color(51, 51, 51));
        winBg.setForeground(new java.awt.Color(255, 255, 255));

        okBtn.setBackground(new java.awt.Color(0, 153, 255));
        okBtn.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        okBtn.setForeground(new java.awt.Color(255, 255, 255));
        okBtn.setText("OK");
        okBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                okBtnActionPerformed(evt);
            }
        });

        cancelBtn.setBackground(new java.awt.Color(0, 153, 255));
        cancelBtn.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        cancelBtn.setForeground(new java.awt.Color(255, 255, 255));
        cancelBtn.setText("Cancelar");
        cancelBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelBtnActionPerformed(evt);
            }
        });

        message.setFont(new java.awt.Font("SansSerif", 1, 24)); // NOI18N
        message.setForeground(new java.awt.Color(255, 255, 255));
        message.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        message.setIcon(new javax.swing.ImageIcon("/home/diego/NetBeans-Proyects/Estructura-de-Datos/src/main/java/com/mycompany/semestre3/unidad3/adminPack/images/x32/agregar.png")); // NOI18N
        message.setText("Agregar articulo");

        jLabel1.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel1.setText("Nombre");

        jLabel2.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel2.setText("Codigo");

        jLabel3.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel3.setText("Precio");

        jLabel4.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel4.setText("Stock");

        nombreIn.setBackground(new java.awt.Color(102, 102, 102));
        nombreIn.setFont(new java.awt.Font("Noto Sans", 0, 14)); // NOI18N
        nombreIn.setForeground(new java.awt.Color(204, 204, 204));
        nombreIn.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(102, 102, 102), 3, true));
        nombreIn.setSelectionColor(new java.awt.Color(0, 102, 255));

        codigoIn.setBackground(new java.awt.Color(102, 102, 102));
        codigoIn.setFont(new java.awt.Font("Noto Sans", 0, 14)); // NOI18N
        codigoIn.setForeground(new java.awt.Color(204, 204, 204));
        codigoIn.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(102, 102, 102), 3, true));
        codigoIn.setSelectionColor(new java.awt.Color(0, 102, 255));

        precioIn.setBackground(new java.awt.Color(102, 102, 102));
        precioIn.setFont(new java.awt.Font("Noto Sans", 0, 14)); // NOI18N
        precioIn.setForeground(new java.awt.Color(204, 204, 204));
        precioIn.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(102, 102, 102), 3, true));
        precioIn.setSelectionColor(new java.awt.Color(0, 102, 255));
        precioIn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                precioInActionPerformed(evt);
            }
        });

        stockIn.setBackground(new java.awt.Color(102, 102, 102));
        stockIn.setFont(new java.awt.Font("Noto Sans", 0, 14)); // NOI18N
        stockIn.setForeground(new java.awt.Color(204, 204, 204));
        stockIn.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(102, 102, 102), 3, true));
        stockIn.setSelectionColor(new java.awt.Color(0, 102, 255));

        javax.swing.GroupLayout winBgLayout = new javax.swing.GroupLayout(winBg);
        winBg.setLayout(winBgLayout);
        winBgLayout.setHorizontalGroup(
            winBgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(message, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, winBgLayout.createSequentialGroup()
                .addGroup(winBgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, winBgLayout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addGroup(winBgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(winBgLayout.createSequentialGroup()
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(nombreIn))
                            .addGroup(winBgLayout.createSequentialGroup()
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(codigoIn))
                            .addGroup(winBgLayout.createSequentialGroup()
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(stockIn))
                            .addGroup(winBgLayout.createSequentialGroup()
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(precioIn))))
                    .addGroup(winBgLayout.createSequentialGroup()
                        .addContainerGap(363, Short.MAX_VALUE)
                        .addComponent(cancelBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(okBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18))
        );
        winBgLayout.setVerticalGroup(
            winBgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, winBgLayout.createSequentialGroup()
                .addComponent(message, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(winBgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nombreIn, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(winBgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(codigoIn, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(winBgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(precioIn, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(winBgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(stockIn, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 86, Short.MAX_VALUE)
                .addGroup(winBgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(cancelBtn, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
                    .addComponent(okBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(winBg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(winBg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /* Eventos de los componentes */
    /**
     * Boton de aceptar.
     * @param evt 
     */
    private void okBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_okBtnActionPerformed
        try {
            articulo.setNombre(nombreIn.getText());
            articulo.setCodigo(Integer.parseInt(codigoIn.getText()));
            articulo.setPrecio(Double.parseDouble(precioIn.getText()));
            articulo.setExistencia(Short.parseShort(stockIn.getText()));
            
            this.request.acceptIsPressed();
        } 
        catch(NumberFormatException e) {
            ErrorDialog.showDialog(parent, "Fallo", "<html><body>Revise los campos, ya que hay un dato incorrecto o invalido.</body></html>");
            return;
        }
        catch(Exception e) {
            ErrorDialog.showDialog(parent, "Fallo critico", "<html><body>"+e.getMessage()+"<br><br><b>"+e.getClass()+"</b></body></html>");
            this.request.windowClosedOrHiden();
        } 
        finally {
            this.setVisible(false);
        }
    }//GEN-LAST:event_okBtnActionPerformed

    /**
     * Boton de cancelar.
     * @param evt 
     */
    private void cancelBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelBtnActionPerformed
        this.request.cancelIsPressed();
        this.setVisible(false);
    }//GEN-LAST:event_cancelBtnActionPerformed

    // No se como quitarlo :(
    private void precioInActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_precioInActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_precioInActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AppendObjDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AppendObjDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AppendObjDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AppendObjDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                AppendObjDialog dialog = new AppendObjDialog(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cancelBtn;
    private javax.swing.JTextField codigoIn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel message;
    private javax.swing.JTextField nombreIn;
    private javax.swing.JButton okBtn;
    private javax.swing.JTextField precioIn;
    private javax.swing.JTextField stockIn;
    private javax.swing.JPanel winBg;
    // End of variables declaration//GEN-END:variables
}
