package com.mycompany.semestre3.unidad3.adminPack.utils;


public class HelpDialog extends javax.swing.JDialog {
    
    /* Atributos */
    DialogWinRequest request;

    /* Metodos */
    /**
     * Constructor por defecto.
     */
    public HelpDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        
        this.setLocationRelativeTo(null);
        this.setResizable(false);
        
    }
    
    /**
     * Mostramos el dialogo, pero esta aun mas simplificado
     * y es mas facil de llamar.
     * @param parent
     * @return 
     */
    public static int showDialog(java.awt.Frame parent) {
        DialogWinRequest request = new DialogWinRequest();
        
        HelpDialog subwin = new HelpDialog(parent, true);
        subwin.setUserRequest(request);
        subwin.setVisible(true);
        
        return request.getRequest();
    }
    
    /**
     * Le pasamos el atributo para establecer la comunicacion
     * y poder obtener una respuesta de acuerdo al parametro 
     * por referencia y el boton pulsado.
     * 
     * @param r 
     */
    public void setUserRequest(DialogWinRequest r) {
        this.request = r;
        request.windowClosedOrHiden();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        winBg = new javax.swing.JPanel();
        acceptBtn = new javax.swing.JButton();
        windowTitle = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        text = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        winBg.setBackground(new java.awt.Color(51, 51, 51));
        winBg.setForeground(new java.awt.Color(255, 255, 255));

        acceptBtn.setBackground(new java.awt.Color(0, 153, 255));
        acceptBtn.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        acceptBtn.setForeground(new java.awt.Color(255, 255, 255));
        acceptBtn.setText("OK");
        acceptBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                acceptBtnActionPerformed(evt);
            }
        });

        windowTitle.setFont(new java.awt.Font("SansSerif", 1, 24)); // NOI18N
        windowTitle.setForeground(new java.awt.Color(255, 255, 255));
        windowTitle.setIcon(new javax.swing.ImageIcon("/home/diego/NetBeans-Proyects/Estructura-de-Datos/src/main/java/com/mycompany/semestre3/unidad3/adminPack/images/x32/solicitud.png")); // NOI18N
        windowTitle.setText("AYUDA");

        jScrollPane1.setBackground(new java.awt.Color(51, 51, 51));
        jScrollPane1.setBorder(null);
        jScrollPane1.setForeground(new java.awt.Color(204, 204, 204));

        text.setBackground(new java.awt.Color(51, 51, 51));
        text.setColumns(20);
        text.setFont(new java.awt.Font("SansSerif", 0, 13)); // NOI18N
        text.setForeground(new java.awt.Color(204, 204, 204));
        text.setLineWrap(true);
        text.setRows(5);
        text.setText("SOBRE EL PROGRAMA\nEste es un programa grafico desarrollado en Java para estudiar el manejo y uso de las estructuras de datos. Este\nprograma no tiene una utilidad real mas alla de servir como medio de aprendizaje.\n\nEN QUE CONSISTE.\nEl programa trata sobre almacenar y gestionar productos en una pila mediante dos operaciones que son \"Agregar\" y \"Eliminar\".\n\nAGREGAR\nA la hora de agregar  un objeto nos pedira ingresar 4 atributos que son:\n\t- Nombre: debe ser un texto de no mas de 30 caracteres\n\t- Codigo: numero entero que identifica el articulo de forma unica\n\t- \n\t-\n");
        text.setCaretColor(new java.awt.Color(51, 102, 255));
        text.setDisabledTextColor(new java.awt.Color(204, 204, 204));
        text.setSelectionColor(new java.awt.Color(0, 153, 255));
        jScrollPane1.setViewportView(text);

        javax.swing.GroupLayout winBgLayout = new javax.swing.GroupLayout(winBg);
        winBg.setLayout(winBgLayout);
        winBgLayout.setHorizontalGroup(
            winBgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(winBgLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(winBgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(winBgLayout.createSequentialGroup()
                        .addGroup(winBgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(winBgLayout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(jScrollPane1))
                            .addComponent(acceptBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(16, 16, 16))
                    .addGroup(winBgLayout.createSequentialGroup()
                        .addComponent(windowTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 501, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(219, Short.MAX_VALUE))))
        );
        winBgLayout.setVerticalGroup(
            winBgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, winBgLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(windowTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 529, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(acceptBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(winBg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(winBg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void acceptBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_acceptBtnActionPerformed
        this.request.cancelIsPressed();
        this.setVisible(false);
    }//GEN-LAST:event_acceptBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HelpDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HelpDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HelpDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HelpDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                HelpDialog dialog = new HelpDialog(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton acceptBtn;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea text;
    private javax.swing.JPanel winBg;
    private javax.swing.JLabel windowTitle;
    // End of variables declaration//GEN-END:variables
}
