package com.d.semestre3.unidad3.cenaduria;

import com.d.semestre3.unidad3.adminPack.utils.ExitDialog;
import java.awt.BorderLayout;
import javax.swing.JPanel;


public class MainForm extends javax.swing.JFrame {
    /* Atributos */
    private Cola cola = new Cola();
    private short actualMenuId = 0;
    
    /* Metodos */
    /**
     * Constructor por defecto
     */
    public MainForm() {
        initComponents();
        
        changeMenuIndicator((short)0);
        setResizable(false);
        this.setLocationRelativeTo(null);
    }
    
    /**
     * Nos muestar un pequeño indicador de la opcion del
     * menu.
     * @param newState 
     */
    private void changeMenuIndicator(short newState) {
        actualMenuId = newState;
        
        this.atenderPedidoIndicator.setVisible(false);
        this.verPedidoIndicator.setVisible(false);
        
        if(actualMenuId == 1) 
            atenderPedidoIndicator.setVisible(true);
        else if(actualMenuId == 2) {
            verPedidoIndicator.setVisible(true);
        }
        
    }
    
    /**
     * Mostramos determinado panel en elespacio de trabajo.
     * @param panel 
     */
    private void showInWorkspace(JPanel panel) {
        panel.setSize(workspace.getWidth(), workspace.getHeight());
        panel.setLocation(0, 0);
        
        workspace.removeAll();
        
        workspace.add(panel, BorderLayout.CENTER);
        workspace.revalidate();
        workspace.repaint();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        windowBackdround = new javax.swing.JPanel();
        sideMenu = new javax.swing.JPanel();
        titleOfSideMenu = new javax.swing.JLabel();
        atenderPedidoOpt = new javax.swing.JButton();
        verPedidosOpt = new javax.swing.JButton();
        salirOpt = new javax.swing.JButton();
        atenderPedidoIndicator = new javax.swing.JPanel();
        verPedidoIndicator = new javax.swing.JPanel();
        workspace = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        windowBackdround.setBackground(new java.awt.Color(255, 255, 255));
        windowBackdround.setForeground(new java.awt.Color(51, 51, 51));
        windowBackdround.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        sideMenu.setBackground(new java.awt.Color(51, 51, 51));
        sideMenu.setForeground(new java.awt.Color(204, 204, 204));

        titleOfSideMenu.setFont(new java.awt.Font("SansSerif", 1, 24)); // NOI18N
        titleOfSideMenu.setForeground(new java.awt.Color(255, 255, 255));
        titleOfSideMenu.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titleOfSideMenu.setText("CENADURIA");
        titleOfSideMenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                titleOfSideMenuMouseClicked(evt);
            }
        });

        atenderPedidoOpt.setBackground(new java.awt.Color(51, 51, 51));
        atenderPedidoOpt.setFont(new java.awt.Font("Noto Sans", 1, 18)); // NOI18N
        atenderPedidoOpt.setForeground(new java.awt.Color(204, 204, 204));
        atenderPedidoOpt.setIcon(new javax.swing.ImageIcon("/home/diego/NetBeans-Proyects/Estructura-de-Datos/src/main/java/com/mycompany/semestre3/unidad3/cenaduria/images/x24/caja-registradora2.png")); // NOI18N
        atenderPedidoOpt.setText("Atender pedido");
        atenderPedidoOpt.setBorder(null);
        atenderPedidoOpt.setBorderPainted(false);
        atenderPedidoOpt.setContentAreaFilled(false);
        atenderPedidoOpt.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        atenderPedidoOpt.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        atenderPedidoOpt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                atenderPedidoOptActionPerformed(evt);
            }
        });

        verPedidosOpt.setBackground(new java.awt.Color(51, 51, 51));
        verPedidosOpt.setFont(new java.awt.Font("Noto Sans", 1, 18)); // NOI18N
        verPedidosOpt.setForeground(new java.awt.Color(204, 204, 204));
        verPedidosOpt.setIcon(new javax.swing.ImageIcon("/home/diego/NetBeans-Proyects/Estructura-de-Datos/src/main/java/com/mycompany/semestre3/unidad3/cenaduria/images/x24/lista.png")); // NOI18N
        verPedidosOpt.setText("Ver pedidos");
        verPedidosOpt.setBorder(null);
        verPedidosOpt.setBorderPainted(false);
        verPedidosOpt.setContentAreaFilled(false);
        verPedidosOpt.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        verPedidosOpt.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        verPedidosOpt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                verPedidosOptActionPerformed(evt);
            }
        });

        salirOpt.setBackground(new java.awt.Color(51, 51, 51));
        salirOpt.setFont(new java.awt.Font("Noto Sans", 1, 18)); // NOI18N
        salirOpt.setForeground(new java.awt.Color(255, 102, 102));
        salirOpt.setIcon(new javax.swing.ImageIcon("/home/diego/NetBeans-Proyects/Estructura-de-Datos/src/main/java/com/mycompany/semestre3/unidad3/cenaduria/images/x24/cerrar-sesion.png")); // NOI18N
        salirOpt.setText("Salir");
        salirOpt.setBorder(null);
        salirOpt.setBorderPainted(false);
        salirOpt.setContentAreaFilled(false);
        salirOpt.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        salirOpt.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        salirOpt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salirOptActionPerformed(evt);
            }
        });

        atenderPedidoIndicator.setBackground(new java.awt.Color(102, 102, 102));

        javax.swing.GroupLayout atenderPedidoIndicatorLayout = new javax.swing.GroupLayout(atenderPedidoIndicator);
        atenderPedidoIndicator.setLayout(atenderPedidoIndicatorLayout);
        atenderPedidoIndicatorLayout.setHorizontalGroup(
            atenderPedidoIndicatorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 8, Short.MAX_VALUE)
        );
        atenderPedidoIndicatorLayout.setVerticalGroup(
            atenderPedidoIndicatorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
        );

        verPedidoIndicator.setBackground(new java.awt.Color(102, 102, 102));

        javax.swing.GroupLayout verPedidoIndicatorLayout = new javax.swing.GroupLayout(verPedidoIndicator);
        verPedidoIndicator.setLayout(verPedidoIndicatorLayout);
        verPedidoIndicatorLayout.setHorizontalGroup(
            verPedidoIndicatorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 8, Short.MAX_VALUE)
        );
        verPedidoIndicatorLayout.setVerticalGroup(
            verPedidoIndicatorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout sideMenuLayout = new javax.swing.GroupLayout(sideMenu);
        sideMenu.setLayout(sideMenuLayout);
        sideMenuLayout.setHorizontalGroup(
            sideMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sideMenuLayout.createSequentialGroup()
                .addGroup(sideMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, sideMenuLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(sideMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, sideMenuLayout.createSequentialGroup()
                                .addComponent(atenderPedidoIndicator, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(atenderPedidoOpt, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, sideMenuLayout.createSequentialGroup()
                                .addComponent(verPedidoIndicator, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(verPedidosOpt, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(salirOpt, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(titleOfSideMenu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        sideMenuLayout.setVerticalGroup(
            sideMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sideMenuLayout.createSequentialGroup()
                .addComponent(titleOfSideMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(sideMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(atenderPedidoOpt, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(atenderPedidoIndicator, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(sideMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(verPedidosOpt, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(verPedidoIndicator, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 565, Short.MAX_VALUE)
                .addComponent(salirOpt, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        windowBackdround.add(sideMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 260, 770));

        workspace.setBackground(new java.awt.Color(204, 204, 204));

        javax.swing.GroupLayout workspaceLayout = new javax.swing.GroupLayout(workspace);
        workspace.setLayout(workspaceLayout);
        workspaceLayout.setHorizontalGroup(
            workspaceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 780, Short.MAX_VALUE)
        );
        workspaceLayout.setVerticalGroup(
            workspaceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 770, Short.MAX_VALUE)
        );

        windowBackdround.add(workspace, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 0, 780, 770));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(windowBackdround, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(windowBackdround, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Evento que invoca el menu de atender pedidos
     * @param evt 
     */
    private void atenderPedidoOptActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_atenderPedidoOptActionPerformed
        if(this.actualMenuId == 1) return;
        
        JPanel panel = new RegistrarPedidosPanel(cola);
        showInWorkspace(panel);
        
        changeMenuIndicator((short)1);
    }//GEN-LAST:event_atenderPedidoOptActionPerformed

    /**
     * Evento para invocar el menu de ver pedidos
     * @param evt 
     */
    private void verPedidosOptActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_verPedidosOptActionPerformed
        if(this.actualMenuId == 2) return;
        
        JPanel panel = new VerPedidoPanel(cola);
        showInWorkspace(panel);

        changeMenuIndicator((short)2);
    }//GEN-LAST:event_verPedidosOptActionPerformed

    /**
     * Evento para salir de la aplicacion
     * @param evt 
     */
    private void salirOptActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salirOptActionPerformed
        if(ExitDialog.showDialog(this) == 1){
            changeMenuIndicator((short)0);
            System.exit(0);
        }
    }//GEN-LAST:event_salirOptActionPerformed

    /**
     * Evento para volver al panel de bienvenida.
     * @param evt 
     */
    private void titleOfSideMenuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_titleOfSideMenuMouseClicked
        JPanel panel = new WelcomePanel();
        showInWorkspace(panel);
        
        changeMenuIndicator((short)0);
    }//GEN-LAST:event_titleOfSideMenuMouseClicked

    /**
     * Main
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel atenderPedidoIndicator;
    private javax.swing.JButton atenderPedidoOpt;
    private javax.swing.JButton salirOpt;
    private javax.swing.JPanel sideMenu;
    private javax.swing.JLabel titleOfSideMenu;
    private javax.swing.JPanel verPedidoIndicator;
    private javax.swing.JButton verPedidosOpt;
    private javax.swing.JPanel windowBackdround;
    private javax.swing.JPanel workspace;
    // End of variables declaration//GEN-END:variables
}
