/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.d.semestre3.unidad3.cenaduria;

/**
 *
 * @author diego
 */
public class WInPedidos extends javax.swing.JFrame {
    
    /* Atributos */
    private Cola cola = new Cola();

    /* Metodos */
    /**
     * Constructor
     */
    public WInPedidos() {
        initComponents();
        appendSubPanels();
    }
    
    private void appendSubPanels() {
        mainContentViwer.addTab("Registrar", new RegistrarPedidosPanel(cola)); // 0
        mainContentViwer.addTab("Ver Pedidos", new VerPedidoPanel(cola));      // 1
        mainContentViwer.addTab("Atender", new AtenderPedidoPanel(cola));      // 2
        
        mainContentViwer.setSelectedIndex(0);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        mainContentViwer = new javax.swing.JTabbedPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        fileMenu = new javax.swing.JMenu();
        salirMenuOpt = new javax.swing.JMenuItem();
        pedidosMenu = new javax.swing.JMenu();
        atenderMenuOpt = new javax.swing.JMenuItem();
        verPedidosMenuOpt = new javax.swing.JMenuItem();
        optionsMenu = new javax.swing.JMenu();
        helpMenu = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));

        jLabel1.setBackground(new java.awt.Color(0, 126, 255));
        jLabel1.setFont(new java.awt.Font("SansSerif", 1, 38)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon("/home/diego/NetBeans-Proyects/Estructura-de-Datos/src/main/java/com/mycompany/semestre3/unidad3/cenaduria/images/x32/restaurant.png")); // NOI18N
        jLabel1.setText("CENADURIA");

        mainContentViwer.setBackground(new java.awt.Color(0, 51, 255));
        mainContentViwer.setForeground(new java.awt.Color(51, 51, 51));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 996, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(mainContentViwer)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(mainContentViwer, javax.swing.GroupLayout.DEFAULT_SIZE, 487, Short.MAX_VALUE)
                .addContainerGap())
        );

        jMenuBar1.setBackground(new java.awt.Color(0, 126, 255));
        jMenuBar1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 1, true));
        jMenuBar1.setForeground(new java.awt.Color(51, 51, 51));
        jMenuBar1.setFont(new java.awt.Font("Noto Sans CJK JP Black", 0, 12)); // NOI18N

        fileMenu.setText("Archivo");

        salirMenuOpt.setText("Salir");
        salirMenuOpt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                salirMenuOptMouseClicked(evt);
            }
        });
        salirMenuOpt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salirMenuOptActionPerformed(evt);
            }
        });
        fileMenu.add(salirMenuOpt);

        jMenuBar1.add(fileMenu);

        pedidosMenu.setText("Pedidos");

        atenderMenuOpt.setBackground(new java.awt.Color(51, 51, 51));
        atenderMenuOpt.setText("Atender");
        atenderMenuOpt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                atenderMenuOptActionPerformed(evt);
            }
        });
        pedidosMenu.add(atenderMenuOpt);

        verPedidosMenuOpt.setText("Ver pedidos");
        verPedidosMenuOpt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                verPedidosMenuOptActionPerformed(evt);
            }
        });
        pedidosMenu.add(verPedidosMenuOpt);

        jMenuBar1.add(pedidosMenu);

        optionsMenu.setText("Opciones");

        helpMenu.setText("Ayuda");

        jMenuItem1.setText("Sobre el programa");
        helpMenu.add(jMenuItem1);

        jMenuItem2.setText("Como se usa");
        helpMenu.add(jMenuItem2);

        optionsMenu.add(helpMenu);

        jMenuItem3.setText("Accesibilidad");
        optionsMenu.add(jMenuItem3);

        jMenuBar1.add(optionsMenu);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void salirMenuOptMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_salirMenuOptMouseClicked
        System.out.println("Hola");
        System.exit(0);
    }//GEN-LAST:event_salirMenuOptMouseClicked

    private void salirMenuOptActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salirMenuOptActionPerformed
        System.out.println("Hola");
        System.exit(0);
    }//GEN-LAST:event_salirMenuOptActionPerformed

    private void verPedidosMenuOptActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_verPedidosMenuOptActionPerformed
        mainContentViwer.setSelectedIndex(1);
    }//GEN-LAST:event_verPedidosMenuOptActionPerformed

    private void atenderMenuOptActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_atenderMenuOptActionPerformed
        mainContentViwer.setSelectedIndex(2);
    }//GEN-LAST:event_atenderMenuOptActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(WInPedidos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(WInPedidos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(WInPedidos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(WInPedidos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new WInPedidos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem atenderMenuOpt;
    private javax.swing.JMenu fileMenu;
    private javax.swing.JMenu helpMenu;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTabbedPane mainContentViwer;
    private javax.swing.JMenu optionsMenu;
    private javax.swing.JMenu pedidosMenu;
    private javax.swing.JMenuItem salirMenuOpt;
    private javax.swing.JMenuItem verPedidosMenuOpt;
    // End of variables declaration//GEN-END:variables
}
