package com.mycompany.semestre3.unidad3.cenaduria;

import javax.swing.JOptionPane;

/**
 *
 * @author diego
 */
public class RegistrarPedidosPanel extends javax.swing.JPanel {
    /* Atributos */
    private Cola cola = null;
    private Pedido pedido = null;

    /* Metodos */
    /**
     * Constructor
     * @param cola 
     */
    public RegistrarPedidosPanel(Cola cola) {
        this.cola = cola;
        initComponents();
    }
    
    private void clearInputs() {
        // Campos del pedido 
        nombreClienteIn.setText("");
        noPedidoIn.setText("");
        direccionIn.setText("");
        telefonoIn.setText("");
        // Cantidad de platillos
        noEnchiladas.setValue(0);
        noTacos.setValue(0);
        noRefrescos.setValue(0);
        noPozole.setValue(0);
        noSopes.setValue(0);
        // Tiket
        tiketText.setText("...");
    }
    
    private boolean checkNumberInputsVal() {
        if(
                (Integer)(noEnchiladas.getValue()) <= 0 &&
                (Integer)(noTacos.getValue()) <= 0 &&
                (Integer)(noRefrescos.getValue()) <= 0 &&
                (Integer)(noPozole.getValue()) <= 0 &&
                (Integer)(noSopes.getValue()) <= 0
        ) {
            JOptionPane.showMessageDialog(null, "No hay ningun platillo agregado. Revise bien el pedido", "Advertencia", JOptionPane.WARNING_MESSAGE);
            return false;
        }
        
        return true;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        titlePanel = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        nombreClienteIn = new javax.swing.JTextField();
        noPedidoIn = new javax.swing.JTextField();
        direccionIn = new javax.swing.JTextField();
        telefonoIn = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        noEnchiladas = new javax.swing.JSpinner();
        noTacos = new javax.swing.JSpinner();
        noRefrescos = new javax.swing.JSpinner();
        noPozole = new javax.swing.JSpinner();
        noSopes = new javax.swing.JSpinner();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        agregarPedidoBtn = new javax.swing.JButton();
        cancelarBtn = new javax.swing.JButton();
        tiketSection = new javax.swing.JPanel();
        tiketTitleLabel = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tiketText = new javax.swing.JTextArea();
        crearTiket = new javax.swing.JButton();
        printTiket = new javax.swing.JButton();

        setBackground(new java.awt.Color(204, 204, 204));
        setForeground(new java.awt.Color(51, 51, 51));

        titlePanel.setFont(new java.awt.Font("sansserif", 1, 24)); // NOI18N
        titlePanel.setForeground(new java.awt.Color(51, 51, 51));
        titlePanel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titlePanel.setIcon(new javax.swing.ImageIcon("/home/diego/NetBeans-Proyects/Estructura-de-Datos/src/main/java/com/mycompany/semestre3/unidad3/cenaduria/images/x32/caja-registradora.png")); // NOI18N
        titlePanel.setText("Registrar pedido");

        jLabel2.setForeground(new java.awt.Color(51, 51, 51));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel2.setText("Cliente");

        jLabel1.setForeground(new java.awt.Color(51, 51, 51));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel1.setText("Numero de pedido");

        jLabel3.setForeground(new java.awt.Color(51, 51, 51));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel3.setText("direccion");

        jLabel4.setForeground(new java.awt.Color(51, 51, 51));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel4.setText("Telefono");

        nombreClienteIn.setBackground(new java.awt.Color(51, 51, 51));
        nombreClienteIn.setForeground(new java.awt.Color(204, 204, 204));
        nombreClienteIn.setSelectionColor(new java.awt.Color(0, 126, 255));

        noPedidoIn.setBackground(new java.awt.Color(51, 51, 51));
        noPedidoIn.setForeground(new java.awt.Color(204, 204, 204));
        noPedidoIn.setSelectionColor(new java.awt.Color(0, 126, 255));
        noPedidoIn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                noPedidoInActionPerformed(evt);
            }
        });

        direccionIn.setBackground(new java.awt.Color(51, 51, 51));
        direccionIn.setForeground(new java.awt.Color(204, 204, 204));
        direccionIn.setSelectionColor(new java.awt.Color(0, 126, 255));

        telefonoIn.setBackground(new java.awt.Color(51, 51, 51));
        telefonoIn.setForeground(new java.awt.Color(204, 204, 204));
        telefonoIn.setSelectionColor(new java.awt.Color(0, 126, 255));

        jSeparator1.setForeground(new java.awt.Color(102, 102, 102));

        jLabel5.setForeground(new java.awt.Color(51, 51, 51));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel5.setText("Enchiladas");

        jLabel6.setForeground(new java.awt.Color(51, 51, 51));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel6.setText("Tacos dorados");

        jLabel7.setForeground(new java.awt.Color(51, 51, 51));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel7.setText("Refrescos");

        jLabel8.setForeground(new java.awt.Color(51, 51, 51));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel8.setText("Pozole");

        jLabel9.setForeground(new java.awt.Color(51, 51, 51));
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel9.setText("Sopes");

        jLabel10.setForeground(new java.awt.Color(0, 51, 0));
        jLabel10.setText("$8 pesos");

        jLabel11.setForeground(new java.awt.Color(0, 51, 0));
        jLabel11.setText("$6 pesos");

        jLabel12.setForeground(new java.awt.Color(0, 51, 0));
        jLabel12.setText("$20 pesos");

        jLabel13.setForeground(new java.awt.Color(0, 51, 0));
        jLabel13.setText("$60 pesos");

        jLabel14.setForeground(new java.awt.Color(0, 51, 0));
        jLabel14.setText("$11 pesos");

        agregarPedidoBtn.setBackground(new java.awt.Color(51, 51, 51));
        agregarPedidoBtn.setForeground(new java.awt.Color(255, 255, 255));
        agregarPedidoBtn.setText("AGREGAR");
        agregarPedidoBtn.setBorderPainted(false);
        agregarPedidoBtn.setEnabled(false);
        agregarPedidoBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agregarPedidoBtnActionPerformed(evt);
            }
        });

        cancelarBtn.setBackground(new java.awt.Color(51, 51, 51));
        cancelarBtn.setForeground(new java.awt.Color(255, 255, 255));
        cancelarBtn.setText("CANCELAR");
        cancelarBtn.setBorderPainted(false);
        cancelarBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelarBtnActionPerformed(evt);
            }
        });

        tiketSection.setBackground(new java.awt.Color(255, 255, 204));
        tiketSection.setForeground(new java.awt.Color(51, 51, 51));

        tiketTitleLabel.setFont(new java.awt.Font("sansserif", 1, 13)); // NOI18N
        tiketTitleLabel.setForeground(new java.awt.Color(51, 51, 51));
        tiketTitleLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        tiketTitleLabel.setText("TICKET");

        tiketText.setEditable(false);
        tiketText.setBackground(new java.awt.Color(255, 255, 204));
        tiketText.setColumns(20);
        tiketText.setFont(new java.awt.Font("sansserif", 0, 12)); // NOI18N
        tiketText.setForeground(new java.awt.Color(51, 51, 51));
        tiketText.setLineWrap(true);
        tiketText.setRows(5);
        tiketText.setBorder(null);
        jScrollPane2.setViewportView(tiketText);

        javax.swing.GroupLayout tiketSectionLayout = new javax.swing.GroupLayout(tiketSection);
        tiketSection.setLayout(tiketSectionLayout);
        tiketSectionLayout.setHorizontalGroup(
            tiketSectionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tiketTitleLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 284, Short.MAX_VALUE)
            .addGroup(tiketSectionLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2)
                .addContainerGap())
        );
        tiketSectionLayout.setVerticalGroup(
            tiketSectionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tiketSectionLayout.createSequentialGroup()
                .addComponent(tiketTitleLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2)
                .addContainerGap())
        );

        crearTiket.setBackground(new java.awt.Color(51, 51, 51));
        crearTiket.setForeground(new java.awt.Color(255, 255, 255));
        crearTiket.setText("Confirmar");
        crearTiket.setBorderPainted(false);
        crearTiket.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                crearTiketActionPerformed(evt);
            }
        });

        printTiket.setBackground(new java.awt.Color(51, 51, 51));
        printTiket.setForeground(new java.awt.Color(255, 255, 255));
        printTiket.setText("Imprimir");
        printTiket.setBorderPainted(false);
        printTiket.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                printTiketActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(cancelarBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(agregarPedidoBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(titlePanel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(noPedidoIn))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(direccionIn, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(telefonoIn, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(nombreClienteIn, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 387, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(noRefrescos, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(noPozole, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(noSopes, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(noTacos, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(noEnchiladas, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jLabel12, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel13, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel14, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel11, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.LEADING))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(crearTiket, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(printTiket, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tiketSection, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(titlePanel, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(nombreClienteIn, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(noPedidoIn, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(direccionIn, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(telefonoIn, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(noEnchiladas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10)
                            .addComponent(crearTiket))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(noTacos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel11)
                            .addComponent(printTiket))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(noRefrescos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel12))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(noPozole, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel13))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(noSopes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel14)))
                    .addComponent(tiketSection, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 16, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(agregarPedidoBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cancelarBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    /* Eventos de los componentes */
    private void noPedidoInActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_noPedidoInActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_noPedidoInActionPerformed

    /**
     * Evento para confirmar y mostrar el tiket, ademas de
     * poder permitir agregar el pedido a la cola.
     * @param evt 
     */
    private void crearTiketActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_crearTiketActionPerformed
        try {
            // Obtener el numero de cada platillo
            short[] noPlatillos = {
                Short.parseShort((Integer)noEnchiladas.getValue()+""),
                Short.parseShort((Integer)noTacos.getValue()+""),
                Short.parseShort((Integer)noRefrescos.getValue()+""),
                Short.parseShort((Integer)noPozole.getValue()+""),
                Short.parseShort((Integer)noSopes.getValue()+"")
            };
            if(!checkNumberInputsVal()) return; // por si hay un pedido vacio

            //  Crear el pedido para mostrarlo en el tiket
            pedido = new Pedido(
                    nombreClienteIn.getText(),
                    Integer.parseInt(noPedidoIn.getText()),
                    direccionIn.getText(),
                    telefonoIn.getText(),
                    noPlatillos

            );

            // Mostrar tiket y habilitar el pedido
            agregarPedidoBtn.setEnabled(true);
            tiketText.setText(pedido.toString());
        } 
        catch(NumberFormatException e) {
            JOptionPane.showMessageDialog(
                null, 
                "En numero de pedido no hay un valor de tipo entero\n"+
                "Ingresa un numero valido", 
                "Advertencia", 
                JOptionPane.WARNING_MESSAGE
            );
        }     
    }//GEN-LAST:event_crearTiketActionPerformed

    /**
     * Evento para cancelar el registro del pedido
     * y limpiar los campos.
     * @param evt 
     */
    private void cancelarBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelarBtnActionPerformed
        // preguntar si se quiere cancelar el pedido
        byte n = (byte)JOptionPane.showConfirmDialog(null, "Cancelar pedido", "¿Seguro que quiere cancelar el pedido?", JOptionPane.YES_NO_OPTION);
        if(n == 1) return;
        
        clearInputs(); // limpiar los campos de texto
        
        agregarPedidoBtn.setEnabled(false);
    }//GEN-LAST:event_cancelarBtnActionPerformed

    /**
     * Evento para agregar el pedido a la cola para ser atendido
     * cuando le corresponda.
     * @param evt 
     */
    private void agregarPedidoBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agregarPedidoBtnActionPerformed
        if(pedido == null) {
            JOptionPane.showMessageDialog(null, "No hay un pedido para agregar!", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
            
        String msg = cola.agregar(pedido);
        if(msg.equals("Ya no se pueden atender mas pedidos!")) {
            JOptionPane.showMessageDialog(null, msg, "Cola LLena!", JOptionPane.ERROR_MESSAGE);
        }
        else {
            JOptionPane.showMessageDialog(null, msg, "OK", JOptionPane.INFORMATION_MESSAGE);
        }
        
        clearInputs();
        agregarPedidoBtn.setEnabled(false);
    }//GEN-LAST:event_agregarPedidoBtnActionPerformed

    /**
     * 
     * @param evt 
     */
    private void printTiketActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_printTiketActionPerformed
        JOptionPane.showMessageDialog(
                null, 
                "No es posible imprimir el tiket\n"+
                "La funcion no esta implementada", 
                "Funcion no disponible", 
                JOptionPane.WARNING_MESSAGE
            );
        
        printTiket.setEnabled(false);
    }//GEN-LAST:event_printTiketActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton agregarPedidoBtn;
    private javax.swing.JButton cancelarBtn;
    private javax.swing.JButton crearTiket;
    private javax.swing.JTextField direccionIn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSpinner noEnchiladas;
    private javax.swing.JTextField noPedidoIn;
    private javax.swing.JSpinner noPozole;
    private javax.swing.JSpinner noRefrescos;
    private javax.swing.JSpinner noSopes;
    private javax.swing.JSpinner noTacos;
    private javax.swing.JTextField nombreClienteIn;
    private javax.swing.JButton printTiket;
    private javax.swing.JTextField telefonoIn;
    private javax.swing.JPanel tiketSection;
    private javax.swing.JTextArea tiketText;
    private javax.swing.JLabel tiketTitleLabel;
    private javax.swing.JLabel titlePanel;
    // End of variables declaration//GEN-END:variables
}
