package com.d.semestre3.unidad2.AlmacenMexico;

import javax.swing.JOptionPane;

/**
 *
 * @author diego
 */
public class MainWin extends javax.swing.JFrame {
    
    /* ------==[ Atributos ]==------ */
    ControlArticulo control = new ControlArticulo();

    /**
     * CONSTRUCTOR
     */
    public MainWin() {
        initComponents();
    }
    
    /* ------==[ Metodos ]==------ */
    /**
     * Le pregunta al usuario si desea salir de la aplicacion.
     * Solo esta aqui para aprendizaje y porque le da un mejor
     * aspecto al programa.
     */
    private void areYouSureExit() {
        int n = JOptionPane.showConfirmDialog(this, "Seguro que desea salir del programa?", "Salir", JOptionPane.YES_NO_OPTION);
        
        if(n == 0) System.exit(0);
    }
    
    private void incompleteFunctionAlert() {
        JOptionPane.showMessageDialog(this, "Este programa esta en desarrollo y esta funcion no esta habilitada.");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        SideMenu = new javax.swing.JPanel();
        appendActionBtn = new javax.swing.JButton();
        deleteActionBtn = new javax.swing.JButton();
        catalogDivTagForSide = new javax.swing.JLabel();
        searchActionBtn = new javax.swing.JButton();
        listActionBtn = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JSeparator();
        movmentDivTagForSide = new javax.swing.JLabel();
        buyActionBtn = new javax.swing.JButton();
        saleActionBtn = new javax.swing.JButton();
        reportActionBtn = new javax.swing.JButton();
        jSeparator3 = new javax.swing.JSeparator();
        closeSeccion = new javax.swing.JButton();
        exitBtn = new javax.swing.JButton();
        closeInternalWin = new javax.swing.JButton();
        windowZone = new javax.swing.JDesktopPane();
        MainMenuBar = new javax.swing.JMenuBar();
        fileSubmenuBar = new javax.swing.JMenu();
        exitAppOptMenu = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        SaveOptMenu = new javax.swing.JMenuItem();
        saveasListOptMenu = new javax.swing.JMenuItem();
        newOptMenu = new javax.swing.JMenuItem();
        seeSubmenuBar = new javax.swing.JMenu();
        settingsSubmenuBar = new javax.swing.JMenu();
        helpSubmenuBar = new javax.swing.JMenu();
        onlinedocOptMenu = new javax.swing.JMenuItem();
        aboutAppOptMenu = new javax.swing.JMenuItem();
        aboutVersion = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        SideMenu.setBackground(new java.awt.Color(51, 51, 51));
        SideMenu.setForeground(new java.awt.Color(255, 255, 255));

        appendActionBtn.setBackground(new java.awt.Color(102, 102, 102));
        appendActionBtn.setForeground(new java.awt.Color(255, 255, 255));
        appendActionBtn.setText("AGREGAR");
        appendActionBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                appendActionBtnActionPerformed(evt);
            }
        });

        deleteActionBtn.setBackground(new java.awt.Color(102, 102, 102));
        deleteActionBtn.setForeground(new java.awt.Color(255, 255, 255));
        deleteActionBtn.setText("ELIMINAR");
        deleteActionBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteActionBtnActionPerformed(evt);
            }
        });

        catalogDivTagForSide.setForeground(new java.awt.Color(255, 255, 255));
        catalogDivTagForSide.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        catalogDivTagForSide.setText("CATALOGO");

        searchActionBtn.setBackground(new java.awt.Color(102, 102, 102));
        searchActionBtn.setForeground(new java.awt.Color(255, 255, 255));
        searchActionBtn.setText("BUSCAR");
        searchActionBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchActionBtnActionPerformed(evt);
            }
        });

        listActionBtn.setBackground(new java.awt.Color(102, 102, 102));
        listActionBtn.setForeground(new java.awt.Color(255, 255, 255));
        listActionBtn.setText("LISTAR");
        listActionBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                listActionBtnActionPerformed(evt);
            }
        });

        movmentDivTagForSide.setForeground(new java.awt.Color(255, 255, 255));
        movmentDivTagForSide.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        movmentDivTagForSide.setText("MOVIMIENTOS");

        buyActionBtn.setBackground(new java.awt.Color(102, 102, 102));
        buyActionBtn.setForeground(new java.awt.Color(255, 255, 255));
        buyActionBtn.setText("COMPRAS");
        buyActionBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buyActionBtnActionPerformed(evt);
            }
        });

        saleActionBtn.setBackground(new java.awt.Color(102, 102, 102));
        saleActionBtn.setForeground(new java.awt.Color(255, 255, 255));
        saleActionBtn.setText("VENTAS");
        saleActionBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saleActionBtnActionPerformed(evt);
            }
        });

        reportActionBtn.setBackground(new java.awt.Color(102, 102, 102));
        reportActionBtn.setForeground(new java.awt.Color(255, 255, 255));
        reportActionBtn.setText("REPORTES");
        reportActionBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reportActionBtnActionPerformed(evt);
            }
        });

        closeSeccion.setBackground(new java.awt.Color(102, 102, 102));
        closeSeccion.setForeground(new java.awt.Color(255, 255, 255));
        closeSeccion.setText("CERRAR SECION");
        closeSeccion.addMouseWheelListener(new java.awt.event.MouseWheelListener() {
            public void mouseWheelMoved(java.awt.event.MouseWheelEvent evt) {
                closeSeccionMouseWheelMoved(evt);
            }
        });

        exitBtn.setBackground(new java.awt.Color(102, 102, 102));
        exitBtn.setForeground(new java.awt.Color(255, 204, 204));
        exitBtn.setText("SALIR");
        exitBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitBtnActionPerformed(evt);
            }
        });

        closeInternalWin.setBackground(new java.awt.Color(102, 102, 102));
        closeInternalWin.setForeground(new java.awt.Color(255, 255, 255));
        closeInternalWin.setText("CERRAR VENTANAS");
        closeInternalWin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closeInternalWinActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout SideMenuLayout = new javax.swing.GroupLayout(SideMenu);
        SideMenu.setLayout(SideMenuLayout);
        SideMenuLayout.setHorizontalGroup(
            SideMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SideMenuLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(SideMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(SideMenuLayout.createSequentialGroup()
                        .addComponent(closeSeccion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(SideMenuLayout.createSequentialGroup()
                        .addGroup(SideMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(deleteActionBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(appendActionBtn, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE))
                        .addGap(7, 7, 7))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, SideMenuLayout.createSequentialGroup()
                        .addComponent(catalogDivTagForSide, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(SideMenuLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(exitBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(SideMenuLayout.createSequentialGroup()
                        .addGroup(SideMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(closeInternalWin, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(reportActionBtn, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(saleActionBtn, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(buyActionBtn, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jSeparator2, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(listActionBtn, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(searchActionBtn, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(movmentDivTagForSide, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                            .addComponent(jSeparator3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        SideMenuLayout.setVerticalGroup(
            SideMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SideMenuLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(catalogDivTagForSide, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(appendActionBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(deleteActionBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(searchActionBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(listActionBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(movmentDivTagForSide)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(buyActionBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(saleActionBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(reportActionBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 126, Short.MAX_VALUE)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 11, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(closeInternalWin, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(closeSeccion, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(exitBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24))
        );

        javax.swing.GroupLayout windowZoneLayout = new javax.swing.GroupLayout(windowZone);
        windowZone.setLayout(windowZoneLayout);
        windowZoneLayout.setHorizontalGroup(
            windowZoneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 813, Short.MAX_VALUE)
        );
        windowZoneLayout.setVerticalGroup(
            windowZoneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        fileSubmenuBar.setText("Archivo");

        exitAppOptMenu.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_Q, 0));
        exitAppOptMenu.setText("Salir");
        exitAppOptMenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                exitAppOptMenuMouseClicked(evt);
            }
        });
        exitAppOptMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitAppOptMenuActionPerformed(evt);
            }
        });
        fileSubmenuBar.add(exitAppOptMenu);
        fileSubmenuBar.add(jSeparator1);

        SaveOptMenu.setText("Guardar");
        SaveOptMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SaveOptMenuActionPerformed(evt);
            }
        });
        fileSubmenuBar.add(SaveOptMenu);

        saveasListOptMenu.setText("Guardar como");
        saveasListOptMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveasListOptMenuActionPerformed(evt);
            }
        });
        fileSubmenuBar.add(saveasListOptMenu);

        newOptMenu.setText("Nuevo");
        newOptMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newOptMenuActionPerformed(evt);
            }
        });
        fileSubmenuBar.add(newOptMenu);

        MainMenuBar.add(fileSubmenuBar);

        seeSubmenuBar.setText("Ver");
        seeSubmenuBar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                seeSubmenuBarMouseClicked(evt);
            }
        });
        MainMenuBar.add(seeSubmenuBar);

        settingsSubmenuBar.setText("Ajustes");
        settingsSubmenuBar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                settingsSubmenuBarMouseClicked(evt);
            }
        });
        MainMenuBar.add(settingsSubmenuBar);

        helpSubmenuBar.setText("Ayuda");

        onlinedocOptMenu.setText("Documentacion");
        helpSubmenuBar.add(onlinedocOptMenu);

        aboutAppOptMenu.setText("Sobre el programa");
        aboutAppOptMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aboutAppOptMenuActionPerformed(evt);
            }
        });
        helpSubmenuBar.add(aboutAppOptMenu);

        aboutVersion.setText("Version");
        aboutVersion.addMouseWheelListener(new java.awt.event.MouseWheelListener() {
            public void mouseWheelMoved(java.awt.event.MouseWheelEvent evt) {
                aboutVersionMouseWheelMoved(evt);
            }
        });
        aboutVersion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aboutVersionActionPerformed(evt);
            }
        });
        aboutVersion.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                aboutVersionKeyPressed(evt);
            }
        });
        helpSubmenuBar.add(aboutVersion);

        MainMenuBar.add(helpSubmenuBar);

        setJMenuBar(MainMenuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(SideMenu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(windowZone))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(SideMenu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(windowZone, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /* ------==[ Eventos de los Widgets ]==------ */
    private void newOptMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newOptMenuActionPerformed
        control = new ControlArticulo();
        
        windowZone.removeAll();
        this.repaint();
    }//GEN-LAST:event_newOptMenuActionPerformed

    private void deleteActionBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteActionBtnActionPerformed
        windowZone.add(new WinDelete(control));
    }//GEN-LAST:event_deleteActionBtnActionPerformed

    /**
     * Evento para salir del programa desde el menu de navegacion
     * lateral.
     * 
     * @param evt 
     */
    private void exitBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitBtnActionPerformed
        this.areYouSureExit();
    }//GEN-LAST:event_exitBtnActionPerformed

    // Este no sirve y no se como borrarlo
    // El IDE no me deja :(
    private void exitAppOptMenuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitAppOptMenuMouseClicked
        this.areYouSureExit();
    }//GEN-LAST:event_exitAppOptMenuMouseClicked

    /**
     * Evento para salir del programa desde el menu de arriba.
     * 
     * @param evt 
     */
    private void exitAppOptMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitAppOptMenuActionPerformed
        this.areYouSureExit();
    }//GEN-LAST:event_exitAppOptMenuActionPerformed

    // Funciones y acciones que no estan implemenmtadas //
    private void SaveOptMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SaveOptMenuActionPerformed
        this.incompleteFunctionAlert();
    }//GEN-LAST:event_SaveOptMenuActionPerformed

    private void saveasListOptMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveasListOptMenuActionPerformed
        this.incompleteFunctionAlert();
    }//GEN-LAST:event_saveasListOptMenuActionPerformed

    private void seeSubmenuBarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_seeSubmenuBarMouseClicked
        this.incompleteFunctionAlert();
    }//GEN-LAST:event_seeSubmenuBarMouseClicked

    private void settingsSubmenuBarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_settingsSubmenuBarMouseClicked
        this.incompleteFunctionAlert();
    }//GEN-LAST:event_settingsSubmenuBarMouseClicked

    /**
     * 
     * @param evt 
     */
    private void appendActionBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_appendActionBtnActionPerformed
        windowZone.add(new WinAppend(control));
    }//GEN-LAST:event_appendActionBtnActionPerformed

    private void searchActionBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchActionBtnActionPerformed
        windowZone.add(new WinSearch(control));
    }//GEN-LAST:event_searchActionBtnActionPerformed

    private void listActionBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_listActionBtnActionPerformed
        windowZone.add(new WinTableInfo(control));
    }//GEN-LAST:event_listActionBtnActionPerformed

    private void closeInternalWinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closeInternalWinActionPerformed
        windowZone.removeAll();
        this.repaint();
    }//GEN-LAST:event_closeInternalWinActionPerformed

    private void buyActionBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buyActionBtnActionPerformed
        windowZone.add(new WinShop(control));
    }//GEN-LAST:event_buyActionBtnActionPerformed

    private void saleActionBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saleActionBtnActionPerformed
        windowZone.add(new WinSale(control));
    }//GEN-LAST:event_saleActionBtnActionPerformed

    private void reportActionBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reportActionBtnActionPerformed
        windowZone.add(new WinCatReport(control));
    }//GEN-LAST:event_reportActionBtnActionPerformed

    private void aboutAppOptMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aboutAppOptMenuActionPerformed
        JOptionPane.showMessageDialog(
                this, 
                "Este programa esta en Beta pero las funciones basicas ya estan\n" +
                "implemntadas con errores minimos. \n\n" + 
                "Esto es el resultado de mucho empeño y esfuerzo, esto esta echo\n" +
                "con muchas ganas y si encuentras errores puedes reportarlos \n" +
                "contactandome. \n\n"+"\t- Serial Designation D"
        );
    }//GEN-LAST:event_aboutAppOptMenuActionPerformed

    private void aboutVersionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aboutVersionActionPerformed
        JOptionPane.showMessageDialog(
                this, 
                "Version: Beta -> Cyn 3 \n" +
                "Java: OpenJDK 22 - 2024 \n" +
                "Desing in: Apache NetBeans 18"
        );
    }//GEN-LAST:event_aboutVersionActionPerformed

    private void aboutVersionKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_aboutVersionKeyPressed
        System.out.println(evt.getKeyChar());
    }//GEN-LAST:event_aboutVersionKeyPressed

    private void aboutVersionMouseWheelMoved(java.awt.event.MouseWheelEvent evt) {//GEN-FIRST:event_aboutVersionMouseWheelMoved
        JOptionPane.showMessageDialog(
                this, 
                "Si has descubierto esto te felicito. \n\n"+
                "Ahora tsu datos son mios *risa maligna*\n" + 
                ">:D"
        );
    }//GEN-LAST:event_aboutVersionMouseWheelMoved

    private void closeSeccionMouseWheelMoved(java.awt.event.MouseWheelEvent evt) {//GEN-FIRST:event_closeSeccionMouseWheelMoved
        JOptionPane.showMessageDialog( this,  "Estoy solo :( ");
    }//GEN-LAST:event_closeSeccionMouseWheelMoved

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainWin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainWin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainWin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainWin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainWin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar MainMenuBar;
    private javax.swing.JMenuItem SaveOptMenu;
    private javax.swing.JPanel SideMenu;
    private javax.swing.JMenuItem aboutAppOptMenu;
    private javax.swing.JMenuItem aboutVersion;
    private javax.swing.JButton appendActionBtn;
    private javax.swing.JButton buyActionBtn;
    private javax.swing.JLabel catalogDivTagForSide;
    private javax.swing.JButton closeInternalWin;
    private javax.swing.JButton closeSeccion;
    private javax.swing.JButton deleteActionBtn;
    private javax.swing.JMenuItem exitAppOptMenu;
    private javax.swing.JButton exitBtn;
    private javax.swing.JMenu fileSubmenuBar;
    private javax.swing.JMenu helpSubmenuBar;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JButton listActionBtn;
    private javax.swing.JLabel movmentDivTagForSide;
    private javax.swing.JMenuItem newOptMenu;
    private javax.swing.JMenuItem onlinedocOptMenu;
    private javax.swing.JButton reportActionBtn;
    private javax.swing.JButton saleActionBtn;
    private javax.swing.JMenuItem saveasListOptMenu;
    private javax.swing.JButton searchActionBtn;
    private javax.swing.JMenu seeSubmenuBar;
    private javax.swing.JMenu settingsSubmenuBar;
    private javax.swing.JDesktopPane windowZone;
    // End of variables declaration//GEN-END:variables
}
